spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/zfile?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
  h2:
    console:
      enabled: ${zfile.debug}
      path: /h2-console
      settings:
        web-allow-others: true
